---
AWSTemplateFormatVersion: '2010-09-09'
Description: (DataCollection) Stack to enable link account to send data to central DataCollectionBus

Parameters:
  # The AWS Organizations ID for the organization that should be allowed to put events on the event bus.
  POrgID:
    Type: String
    Description: The AWS Organizations ID for the organization that should be allowed to put events on the event bus.

  # S3 Bucket for ingestion
  DataCollectionBucket:
    Type: String
    Description: S3 Bucket for ingestion

  # S3 Bucket kms arn
  DataCollectionBucketKmsArn:
    Type: String
    Default: "N"
    Description: Enter KMS Arn if bucket is encrypted by KMS(Type N for SSE encryption)

Conditions:
  DataCollectionBucketKmsArn: !Not [!Equals [!Ref DataCollectionBucketKmsArn, "N"]]

Resources:
  # Define an AWS Events Event Bus for DataCollection
  DataCollectionBus:
    Type: "AWS::Events::EventBus"
    Properties:
      Name: !Sub DataCollectionBus-${AWS::AccountId}

  # Define the policy for the event bus to allow all accounts from the specified organization to put events
  DataCollectionBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref DataCollectionBus
      StatementId: AllowAllAccountsInOrganizationToPutEvents
      Statement:
        Effect: "Allow"
        Principal: "*"
        Action: "events:PutEvents"
        Resource: !GetAtt DataCollectionBus.Arn
        Condition:
          StringEquals:
            aws:PrincipalOrgID: !Ref POrgID

  # Define an IAM Role for the Kinesis Firehose delivery stream
  KinesisFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole 
      Policies:
        # Policy allowing CloudWatch Logs access
        - PolicyName: cloudwatch-logs-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/*"
        # Policy allowing S3 access
        - PolicyName: AllowS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowS3Access
                Effect: Allow
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${DataCollectionBucket}"
                  - !Sub "arn:${AWS::Partition}:s3:::${DataCollectionBucket}/*"
        # Policy allowing KMS access
        - !If
          - DataCollectionBucketKmsArn
          - PolicyName: AllowkmsAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Sid: AllowKMSAccess
                  Effect: Allow
                  Action:
                    - "kms:Encrypt"
                    - "kms:Decrypt"
                    - "kms:ReEncrypt*"
                    - "kms:GenerateDataKey*"
                  Resource:
                    - !Ref DataCollectionBucketKmsArn
          - !Ref AWS::NoValue

  # Define an AWS Kinesis Firehose Delivery Stream for data ingestion
  KinesisFirehose:
    Type: "AWS::KinesisFirehose::DeliveryStream"
    Properties:
      DeliveryStreamName: !Sub "DataCollection-${AWS::AccountId}-${AWS::Region}"
      DeliveryStreamType: "DirectPut"
      DeliveryStreamEncryptionConfigurationInput:
        KeyType: AWS_OWNED_CMK
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub "arn:${AWS::Partition}:s3:::${DataCollectionBucket}"
        RoleARN: !GetAtt KinesisFirehoseRole.Arn
        Prefix: "DataCollection-data/!{partitionKeyFromQuery:source}/!{timestamp:yyyy}/!{timestamp:MM}/!{timestamp:dd}/"
        CompressionFormat: "UNCOMPRESSED"
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 64
        ErrorOutputPrefix: "DataCollection-error/"
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: "DataCollectionFirehoseLogs"
          LogStreamName: "DataCollectionFirehoseStream"
        DynamicPartitioningConfiguration:
          Enabled: true
          RetryOptions:
            DurationInSeconds: 300
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: AppendDelimiterToRecord
            - Type: MetadataExtraction
              Parameters:
                - ParameterName: MetadataExtractionQuery
                  ParameterValue: "{source:.source}"
                - ParameterName: JsonParsingEngine
                  ParameterValue: JQ-1.6

  # Define an IAM Role for the AWS Events Rule
  DataCollectionRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        # Policy allowing the role to put records to the Kinesis Firehose
        - PolicyName: !Sub "DataCollectionRule-${AWS::AccountId}-${AWS::Region}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "firehose:PutRecord"
                  - "firehose:PutRecordBatch"
                Resource: 
                  - !GetAtt KinesisFirehose.Arn

  # Define an AWS Events Rule for DataCollection
  DataCollectionRule:
    Type: AWS::Events::Rule
    Properties:
      Description: DataCollectionRule
      EventBusName: !Ref DataCollectionBus
      EventPattern:
        source:
          - aws.health
          - awshealthtest
      Name: !Sub "DataCollectionRule-${AWS::AccountId}-${AWS::Region}"
      State: ENABLED
      Targets:
        - Id: DataCollectionRule
          Arn: !GetAtt  KinesisFirehose.Arn
          RoleArn: !GetAtt DataCollectionRuleRole.Arn

Outputs:
  # Output the ARN of the created Data Collection Bus
  DataCollectionBusArn:
    Value: !GetAtt DataCollectionBus.Arn
    Export:
      Name: DataCollectionBusArn




const AWS = require('aws-sdk');
const qs = new AWS.QuickSight();
const s3 = new AWS.S3();
const ses = new AWS.SES();

exports.handler = async (event, context, callback) => {
  try {
    // Use QuickSight API to generate a report and export it to S3.
    const exportParams = {
      AwsAccountId: 'YOUR_ACCOUNT_ID',
      Namespace: 'default',
      ReportId: 'YOUR_REPORT_ID',
      S3Destination: {
        Bucket: 'YOUR_S3_BUCKET',
        Prefix: 'report_exports/',
      },
    };
    const exportResponse = await qs.createTemplateAlias(exportParams).promise();

    // Generate a pre-signed URL to the exported report in S3.
    const s3Params = {
      Bucket: 'YOUR_S3_BUCKET',
      Key: 'report_exports/YOUR_REPORT_NAME.pdf', // Update with the actual report name
    };
    const downloadUrl = await s3.getSignedUrlPromise('getObject', s3Params);

    // Send the report via email using SES.
    const emailParams = {
      Destination: {
        ToAddresses: ['recipient@example.com'],
      },
      Message: {
        Body: {
          Text: {
            Data: `Download your QuickSight report here: ${downloadUrl}`,
          },
        },
        Subject: {
          Data: 'Your QuickSight Report',
        },
      },
      Source: 'sender@example.com',
    };
    await ses.sendEmail(emailParams).promise();

    callback(null, 'Report sent successfully!');
  } catch (error) {
    console.error('Error:', error);
    callback(error);
  }
};
